language: python

services:
  - docker

before_script:
  - docker-compose up -d
  
script:
  - sleep 2
  - python3 test.py

after_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker push "${DOCKER_USERNAME}"/http-server
  - docker-compose down
