version: '3'

services:
  simple-server-cached:
    build: .
    image: ekirillm/http-server
    volumes:
    - /var/log:/var/log
    ports:
    - "2000:65432"
    environment:
    - PREFIX=OK
    depends_on:
    - host-redis
    - server-mongo

  host-redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
    - "7000:6379"
    volumes:
    - ./storage/redis/data:/data

  server-mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - ./storage/mongo/data:/data/db

